### PR TITLE
Adding Diwali assets

### PR DESCRIPTION
**Pull request by AG4lyf**

### CODE REVIEW

**Review by gustavwilliam — COMMENTED** [review]
Thank you for this contribution! I have viewed the pngs and they look good. Do we need all of these sizes, though?

I see you've added the same files in multiple places. I think it would be nice to have the same file in only one place, so it's easier to maintain. Since I both assume we won't be modifying this later on and appreciate having them accessible in both logical places, I won't request changes on this. It's more of a general comment about having it in multiple places and mentioning that it would be nice to have the exact same file in only one place.

**Comment by AG4lyf** [comment]
I took the reference from `easter` directory. as shown it also had the same layout I decided to go with same things. 
I don't think there is any issue having multiple sizes tho.

**Comment by Akarys42** [comment]
Well, one of the downside would be the repo size, if we don't need the different sizes, then why should we have them? We can rerender the svg at any time.

Although, no need to delete them now, since they are in the history. It isn't a big deal anyway.

I really like the assets, very good job!

**Comment by gustavwilliam** [comment]
Okay. It'll probably be fine to store them in multiple places this time.

@Akarys42 yes, that's exactly the reason for including only the necessary versions. If any new ones are needed, there are (hopefully) source files to generate them from. That may be something to keep in mind in the future.

**Review by gustavwilliam — DISMISSED** [review]
Great work! I like it.

**Comment by SebastiaanZ** [comment]
Where did you find the assets for these icons?

**Comment by AG4lyf** [comment]
I don't actually remember the pin point location of them 
but I am pretty sure they are free to use.

**Comment by AG4lyf** [comment]
Ok I found the source with reverse image search 
https://www.freepik.com/free-vector/colorful-mandala-with-floral-shapes_974305.htm
it states `Free for personal and commercial purpose with attribution. ` . Wonder how can we attribute this ?

**Comment by SebastiaanZ** [comment]
In this case, we can add attribution to the readme, in the licenses section, and link back to the original source. Add a comment that this attribution holds for the assets in the diwali folder (see how we do it for lemoji in the readme) and mention that the work is derivative (as opposed to using the asset as-is).

**Review by Kronifer — DISMISSED** [review]
Everything looks great!

**Comment by AG4lyf** [comment]
i think with this 
the pr is ready to be merged.
stale.

**Review by lemonsaurus — APPROVED** [review]
Gorgeous assets. Attribution looks adequate. Let's merge.

**Pull request merged**
