### PR TITLE
Fix okhandbutflipped emoji

### LINKED ISSUE #90: okhandbutflipped blurry not identical to default emoji
## Issue
The `okhandbutflipped` emoji is not identical to the default `ok_hand` emoji.

## Summary
When viewed side-by-side it is clear that the flipped emoji is a little blurry, as well as being thicker and generally different enough that a few users complained about it.

image

### PR DESCRIPTION
**Pull request by gustavwilliam**
Closes #90.

Updates the emoji to use the current okhand twemoji. This is how the new emoji looks:
okhandbutflipped

### CODE REVIEW

**Review by Akarys42 — APPROVED** [review]
Oooooooooh yes! Let’s make them match!

**Comment by Akarys42** [comment]
Actually, it seems like you left from white background behind, can you get rid of it please?

**Comment by gustavwilliam** [comment]
Good catch.

**Comment by gustavwilliam** [comment]
@Akarys42 good catch; fixed!

**Review by Akarys42 — APPROVED** [review]
Updated!

**Pull request merged**
