### PR TITLE
Add blinking logos for guild icon

### PR DESCRIPTION
**Pull request by Denayder**
Heyo! I read in #meta that you guys are looking for more animated logos, and I thought I'd give it a shot. I came up with this, and I hope it's okay :)

I can make whatever changes and tweaks requested, if the idea for the icon is accepted 😁 

I hope you like it. Thank you for reading and considering this. 😁

### CODE REVIEW

**Comment by Denayder** [comment]
> Looks good to me!
> 
> For the sake of consistency with the other animations we have, could you also export one in 1024 x 1024 resolution, named `blinky.gif`?

Ah, missed that one! Thank you for the positive feedback 😁

**Comment by Denayder** [comment]
> Looks nice! Can you add a 5 second pause to the end of this animation, following the conventions established by the other animated logos? For example, it can blink 6 or 8 times, and then take a 4 second break. During this break it should display the default logo. It's also important that the first frame of the gif is our regular logo (not sure if that's the case here), so that it will display correctly when not hovering.
> 
> Otherwise this is good work!

Hey Lemon! Thank you very much for the positive feedback. I believe I made the changes that you requested. If you have additional feedback, please feel free to let me know and I'll get right on it 😁 

Side note: I'm not sure how I dismissed the review thing, but it wasn't intentional haha 😅

**Comment by Akarys42** [comment]
Hi, also don’t forget to update the [evergreen attributes](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/evergreen/__init__.py) so your new logo can be used! (Pretty cool logo btw)

**Comment by Denayder** [comment]
> Don't worry about that, reviews automatically get dismissed when new changes are made. This is because the old review is then considered _stale_, as in, it's no longer good.

Ahh, thank you for the explanation. That makes sense 😁 

> This looks better, but the pause seems to be around 3 seconds. can you make it 4 seconds? I'd be happy to approve it at that point. It looks like I wrote both 5 and 4 seconds in the previous request, sorry about that. 4 is what we want.

Phew, looks like I need to learn how to count properly haha - It now waits exactly 4 seconds before continuing to the next one. 😄 

> Hi, also don’t forget to update the [evergreen attributes](https://github.com/python-discord/seasonalbot/blob/master/bot/seasons/evergreen/__init__.py) so your new logo can be used! (Pretty cool logo btw)

Ahh yeah! Thank you for the reminder! I'll get that done once this gets approved 😁

**Pull request merged**
