### PR TITLE
Update lesbian logo

### PR DESCRIPTION
**Pull request by gdude2002**
This updates the lesbian logo in the `animated` directory, to address the concerns of a user in `#meta`.

I don't have the tools or knowledge to create the GIF - there are tons of free tools out there, but most of them seem limited in resolution, frame rate, or watermarking.

If anyone has any idea what to use for that, though, I'm happy to give it a stab.

### CODE REVIEW

**Comment by MarkKoz** [comment]
It bothers me that the formatting of the svg file is a bit messy now. A simple way would have been to copy another icon that has 5 stripes, open the svg in a text editor, and change the fill colour of the stripes. That's how I made most of the icons once I had the "template" for each number of stripes.

For the GIF, I used photoshop. That's what the PSD is for. However, I understand Photoshop is not free.

**Comment by gdude2002** [comment]
I've updated the SVG as you suggested - I noticed that the way the two outer colours were shown in the other logos didn't match what I did, so I've fixed that as well.

I don't have Photoshop, but I do have Affinity Photo - maybe I can do it in that.

**Comment by gdude2002** [comment]
For the record, though, there's no PSD that I can see.

**Comment by j03b** [comment]
Yeah we don't have the PSDs in the repo anymore.

**Comment by gdude2002** [comment]
There's a PSD in @MarkKoz's PR, #18 - should I use this, or were there changes between then and now?

**Comment by MarkKoz** [comment]
Must have been deleted when we cleaned up the repos. You can find it [here](https://github.com/MarkKoz/branding/blob/18069719fb66f61ed2fd3d42820bb34de51cfa04/logos/logo_seasonal/pride_animated/logo_pride.psd).

Sorry for being nitpicky, but your change still doesn't seem right. I meant that you can copy an entire svg like [this one](https://github.com/gdude2002/branding/blob/master/seasonal/pride/animated/logo_genderfluid/logo_genderfluid.svg?short_path=876272c) and change the fills. This can all be done in a text editor.

**Comment by gdude2002** [comment]
That's alright - I see what you mean, Affinity has made it significantly more complicated. I'll do that.

**Comment by MarkKoz** [comment]
I don't mind making the gif if your tool is giving you trouble.

**Comment by gdude2002** [comment]
Unfortunately, it turns out the Affinity suite doesn't actually support creating animated GIFs. Yikes.

If you wouldn't mind, I'd appreciate that.

**Comment by MarkKoz** [comment]
Here it is. I didn't use git cause it'd take a while to clone the repo. I think the frame timings in the PSD are incorrect. I ended up opening the GIF instead and editing that.

logo_pride

**Comment by gdude2002** [comment]
Oh, nicely done \o/

Do you want to PR it to my fork, or should I just commit it here for you?

**Comment by MarkKoz** [comment]
I forgot about the web interface, sorry. Unfortunately, I cannot upload it to your fork because `File uploads require push access to this repository.` I don't mind you just commit it yourself. Trying to take the path of least resistance.

**Comment by gdude2002** [comment]
Okay, I've done that. That should be everything, right?

**Comment by gdude2002** [comment]
Not a problem at all, you were absolutely right!

**Pull request merged**
