### PR TITLE
Add social banners without any background

### LINKED ISSUE #29: Create a blank social banner for external services.
The social banners setup for our Repos are suitable as a patterned social backdrop on external services such as Reddit. For this purpose, we should have a blank version of these to be able to be used, created from the PSD that exists:
https://github.com/python-discord/branding/tree/master/logos/social_banner

### PR DESCRIPTION
**Pull request by Akarys42**
Hi, as asked in #29, here are the socials banners without any background

This PR closes #29

### CODE REVIEW

**Comment by scragly** [comment]
@Akarys42 I believe you're still mistaken about what the original issue is asking for. I'm asking for the basic banner with **only** the background, no text. You've done the opposite here.

**Comment by cutted** [comment]
Do you need this done still?
ie
image

**Comment by scragly** [comment]
@cutted I appreciate the offer, and what you have is indeed matching the request, however as @Akarys42 has been assigned and it's been only a small amount of time, it's not appropriate to give the task to others.

**Comment by Akarys42** [comment]
Oh, okay I'm so sorry, I don't know why I had so much trouble understanding this. I preferred to open another PR: #32 (I invalided this one)

**Pull request closed without merging**
