### PR TITLE
Create Python Logo_trivia-08.png

### PR DESCRIPTION
**Pull request by xkawixgirlx**
This is the Trivia Logo.

### CODE REVIEW

**Comment by Shivansh-007** [comment]
1. This is a icon, and  hence should go into `icons/trivia_quiz`.
2. Can you also include a `.svg` of the Icon?
3. The files should be formatted this way: `trivia-quiz-dist.png` and `trivia-quiz-src.svg`

**Review by xkawixgirlx — COMMENTED** [review]
Here is the fixed commit and pull to repo. 
File has been deleted from previous location and moved to proper location.
Proper file names have been added.
SVG file type has been added.

**Review by Shivansh-007 — APPROVED** [review]
Thanks! Looks Good To Me!

**Review by lemonsaurus — APPROVED** [review]
Looks great! Thanks for this contribution. ❤️

**Pull request merged**
