### PR TITLE
Add Support For Multiple Banners

### PR DESCRIPTION
**Pull request by HassanAbouelela**
Adds support for having multiple banners per event, similar to icons.

This should be merged at the same time as python-discord/bot#2153.

### CODE REVIEW

**Review by ChrisLovering — DISMISSED** [review]
Very cool, looks good, thanks Scale.

We should hold off on merging this until the same day as the bot side is merged though.

**Review by lemonsaurus — DISMISSED** [review]
Yep, looks good.

**Review by gustavwilliam — COMMENTED** [review]
The branding for Eid has been merged, so we just need to update that banner config before merging this PR.

Other than that, LGTM! Good work.

**Comment by HassanAbouelela** [comment]
Merged main into the branch. Only new branding asset that needed handling was the eid_al_fitr banner. Everything else was merged with no conflicts.

**Pull request merged**
