### PR TITLE
Add lemon_starstruck lemoji

### PR DESCRIPTION
**Pull request by v1nam**
Added lemoji `:lemon_starstruck:`, 
This is how the 128x128 png looks like-
lemon_starstruck
PR for the issue #114

### CODE REVIEW

**Review by gustavwilliam — CHANGES_REQUESTED** [review]
Thanks! Over all, this looks great. I just have two minor comments:
- The mouth color is pretty light. Check out some of the other lemojis and see what color we often use to bring contrast to the mouth
- The mouth is not symmetrically rotated. Could you try to align it properly?

**Review by lemonsaurus — DISMISSED** [review]
Approved, but I agree with @gustavwilliam's comments and want to see that addressed before merge.

**Comment by v1nam** [comment]
So I took the mouth from `:lemon_pleased:`, and aligned it properly like it is on other lemojis
lemon_starstruck
Though the color still seems light, and the next shade of brown makes it a bit darker, so I was wondering what color i can actually use

**Comment by lemonsaurus** [comment]
that seems fine to me. I think this is ready to merge, when you commit the changes.

**Comment by gustavwilliam** [comment]
@v1nam I'd recommend `#422C01` for the mouth. Try that color (or something similar) and I'll happily approve it. The alignment sure works in this version.

**Review by gustavwilliam — APPROVED** [review]
Looks excellent! Well done.

**Pull request merged**
