### PR TITLE
Add Repositories Social Media Previews [V2 HERE]

### PR DESCRIPTION
**Pull request by Akarys42**
As said in the issue #16, " GitHub introduced a feature that allows repository owners to customize the preview that gets shown for social media embeds when a repository is shared".

I decided to go for a gray background, the github logo, the server banner and the repo name underneath.

Here are two examples : 
social_banner_code-jam
social_banner_branding

I also included a template file. I've used the font "brokman" (from http://legionfonts.com/fonts/brokman-black) because I wasn't able to find the original font.

### CODE REVIEW

**Comment by lemonsaurus** [comment]
I like the font you chose, and the hard shadow. I like the background. This is a great start.

I don't like the blurple octocat. There's something about it that just does not work at all for this, in my opinion. I don't like that it's blurple, I don't like its size or its position.

Could you try a few options for that? Maybe we skip the octocat completely, maybe we put it somewhere else, maybe it should be a different color, maybe a bigger PyDis logo? I'm not exactly sure what to change but it's something to do with that GitHub octocat.

Feel free to call on us in #meta and we can figure out a design that works for us all. You're close, but not quite there yet.

**Comment by MarkKoz** [comment]
The three elements have too similar visual weights which makes this design lose focus. I think the most important element to focus on is the repository's name. But it should still be clear that it's for Python Discord and that it's a GitHub repository, just more subtly somehow. The text from the Python Discord logo may be too distracting; perhaps you could get away with only the blurple logo?

I'm not much of a graphic designer so I don't have a concrete solution.

**Comment by scragly** [comment]
The font of the original logotype is Uni Sans. The font used here and the logotype's font being slightly different makes it feel like an attempted imitation rather than a cohesive whole. The font should either be different enough to contrast against the logotype, or should be the exact same one, so if it could be adjusted to Uni Sans, I think it would be an improvement, even if seemingly subtle at first.

The size of the preview should match also the [card template](https://github.com/python-discord/branding/issues/16#issuecomment-491132532) that @sco1 posted over in the issue (1280x640), as the template isn't unnecessarily long which makes the preview embed a nicer size.

**Comment by jos-b** [comment]
Maybe we can have the pydis logo background (the one below without the text):



and white text in uni sans in the centre. I don't think we need the GitHub or Python Discord banner on there.

**Comment by lemonsaurus** [comment]
I like @jos-b's suggestion, and would like to see how that would look.

If you have photoshop, you should be able to very easily just use https://github.com/python-discord/branding/blob/master/logos/social_banner/social_banner.psd as a starting point.

**Comment by Akarys42** [comment]
V2 is ready ! What do you think of it ?
test
image

I've resized the preview to the correct size because I can't press the right touch (now it's larger than the older :D) and I changed the style of the repo name to increase it visual weight.

**Comment by Akarys42** [comment]
V2 is ready ! What do you think of it ?

test

**Comment by LordHemlock** [comment]
In terms of the background, I do think the bigger Python symbols are much more pleasing to the eye.  With the older style, the smaller ones almost become noise unless you're really looking at them, where as the larger ones "pop" more.

**Comment by lemonsaurus** [comment]
I like it.

**Comment by jos-b** [comment]
I like it as well.

**Comment by jos-b** [comment]
Regarding Hemlocks comments I personally prefer the smaller background because at the end of the day we do just want a blurplish noise in the background.

**Comment by Akarys42** [comment]
@SebastiaanZ the older files are still there, I already moved them in an `old` folder. I decided to go for a bigger background to keep the focus on the repo name instead of the background. Don't forget that the preview will be much smaller inside discord (you can try to put a link to `https://github.com/Akarys42/branding` if you want to know how it look inside a conversation if you want).

**Comment by sco1** [comment]
The old png file is gone, there are only 2 psd files in the directory.

**Comment by Akarys42** [comment]
Yeah there is the old preview and the first version of the model that I'm working on. I deleted the png file because there are very very easy to recreate with the psd file. If you want once I'm on my pc I will read them :D

**Comment by SebastiaanZ** [comment]
The reason we have .png files in these repos is because we can use the files directly, instead of having to open them in Photoshop or GIMP to export a version. 

It's okay to add new files, but leave the old files in place as well. We don't want to lose the old files. By the way, instead of creating a new version, just make sure that your PR doesn't delete it from the repo.

**Comment by Akarys42** [comment]
Old preview is back :D

**Pull request merged**
