### PR TITLE
Add :lemon_angrysad:

### PR DESCRIPTION
**Pull request by Atharv-Attri**
Added the emoji :lemon_angrysad:
lemon_angrysad

The size of the png in dist is 128x128.

### CODE REVIEW

**Review by gustavwilliam — COMMENTED** [review]
Thanks! The dimensions and vectorisation work, and I think you arrived at something pretty nice.

The only thing I'd like to see changed is the mouth color. I see that you are already using a slightly darker color for it, but it would be nice to make it even darker, in order to bring som contrast. I've personally used `#422C01` before, but you can check out what precise colors you think fit and have a look at older lemojis as reference.

**Comment by Atharv-Attri** [comment]
Updated!

**Comment by Atharv-Attri** [comment]
wait nvm, srry, forgot to resize it

**Comment by Atharv-Attri** [comment]
There, fixed now!
lemon_angrysad

**Review by gustavwilliam — APPROVED** [review]
Thanks! This is starting to look pretty good.

This is what the lemoji looks like in use:
Screenshot 2021-03-05 at 10 00 43

**Pull request merged**
