### PR TITLE
Bigger numbers in winter logo and readability improvments

### PR DESCRIPTION
**Pull request by Harbys**
Old:
image
 New:
image

### CODE REVIEW

**Review by MrHemlock — APPROVED** [review]
Beautiful as always.  Let's do this thing.

**Comment by gustavwilliam** [comment]
@Harbys did you decrease the value of the numbers? They look slightly dimmer in this newer version.

**Comment by Harbys** [comment]
> 
> 
> @Harbys did you decrease the value of the numbers? They look slightly dimmer in this newer version
Yes for python logo, I feel like it makes the outline more readable
Xmas tree is the same but appears dimmer because of lower mesh density caused by increased number size

**Comment by MarkKoz** [comment]
Can the border avoid overlapping the numbers at least vertically (like the original) if not in both directions?

**Comment by Harbys** [comment]
Yes and No. gifs are limited to 256 color so I can't use shading/transparency to hide it so the only option is to remove numbers that are too close to the outline and that makes it look empty

**Comment by MarkKoz** [comment]
I mean by removing and realigning the numbers rather than using any sort of transparency.

**Comment by gustavwilliam** [comment]
@Harbys I personally think the brighter colors work better. There's not enough contrast in the new version.

This is just things to make it even better. The icon is great. It's easy to get caught in critiquing and not spreading enough positivity.

In my opinion, it would look better to make the colors at least slightly sharper again.

**Comment by Harbys** [comment]
@MarkKoz That would require redoing the whole numbers mesh again and playing with scale. Might do it later this week. Don't have enough time now.

@gustavwilliam I can play around with emission values and we'll see. Just keep in mind that what made last years icon pop was bloom effect and it can't be done due to gif format limitations

**Comment by janine9vn** [comment]
I disagree here @gustavwilliam . I think darkening the inside colors makes the border sharper and makes it a bit more apparent as the Python logo. This was the consensus as well for half a dozen people in the voice chat when reviewing this. 

I think as it stands currently for a animated server icon, it's great.

**Comment by gustavwilliam** [comment]
@janine9vn True, regarding the visibility of the python logo element. I still think it's a bit too dark, however, but as long as the consensus is that the dark logo is better, we should go with that one.

**Comment by Den4200** [comment]
I agree with @janine9vn here, the darkened inside colors make the outer border much more apparent than before. I think it looks much better and the darkness is at the perfect level.

**Pull request merged**
